version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./srv/uptime-kuma-data:/app/data
    ports:
      - 5000:3001  # <Host Port>:<Container Port>
    restart: always
